version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=development_secret_key
      - FLASK_DEBUG=true
      - HOST=0.0.0.0
      - PORT=5000
      - CRONBAT_MAX_EXECUTIONS=20
      - CRONBAT_DB_PATH=/data/cronbat.db
      - CRONBAT_LOGS_PATH=/data/logs
    restart: unless-stopped
    volumes:
      - backend_data:/data
      - ./backend:/app  # Mount source code for development

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_SOCKET_URL=http://localhost:5000
    volumes:
      - ./frontend:/app  # Mount source code for development

volumes:
  backend_data:
