version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=production_secret_key_change_me
      - FLASK_DEBUG=false
      - HOST=0.0.0.0
      - PORT=5000
    restart: unless-stopped
    volumes:
      - backend_data:/app/instance

  frontend:
    build: ./frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_SOCKET_URL=http://localhost:5000

volumes:
  backend_data:
