version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:backend
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    volumes:
      - ../backend:/app:cached
    environment:
      - SECRET_KEY=dev_secret_key
      - FLASK_DEBUG=true
      - HOST=0.0.0.0
      - PORT=5000
    command: python run.py
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    volumes:
      - ../frontend:/app:cached
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_SOCKET_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - backend
